modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/dhyces/InventoryTabs/issues"
[[mods]]
modId="inventorytabs"
version="${file.jarVersion}"
displayName="Inventory Tabs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/inventory-tabs-forge"
logoFile="icon.png"
authors="KQP, LiamMCW, Andrew6rant (Andrew Grant), dhyces"
description='''
Adds tabs to your inventory that lead to nearby blocks.
'''
